#! /bin/sh

sxhkd &

bspc config merge_overlapping_monitors true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

bspc rule -a discord desktop=^6
bspc rule -a Slack desktop=^7

xsetroot -cursor_name left_ptr

feh --bg-center ~/Pictures/Wallpapers/monogatari.png

$HOME/.config/polybar/launch.sh

nm-applet &

xmodmap ~/.Xmodmap

redshift &

fcitx -d

xinput --set-prop "TPPS/2 IBM TrackPoint" "Device Accel Constant Deceleration" 0.6


# Hack for spotify
bspc config external_rules_command ~/.config/bspwm/electron_rules
