#!/bin/sh

sxhkd &

bspc config merge_overlapping_monitors true

bspc monitor DVI-D-0 -d 一 二 三 四 五 
bspc monitor DP-2 -d 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

bspc rule -a discord desktop=^6
bspc rule -a Slack desktop=^6

xsetroot -cursor_name left_ptr

feh --bg-center ~/.config/wallpapers/yiNFzA4.png

$HOME/.config/polybar/launch.sh

redshift &

# Hack for spotify
bspc config external_rules_command ~/.config/bspwm/electron_rules

fcitx -d

bspc config focus_follows_pointer true

xset m 0 0
